# AWS Playbook
---
- name: Configure Database 
  hosts: database
  gather_facts: true
  become: true
  remote_user: ubuntu
  tasks:
    - name: Synchronise files between controller database
      ansible.posix.synchronize:
        src: /home/ubuntu/application/environment/db_env
        dest: /home/ubuntu/
      tags: ['never', 'ec2-configure', 'ec2-database']

    - name: run provision file
      command: /bin/sh "/home/ubuntu/db_env/provision.sh"
      tags: ['never', 'ec2-configure', 'ec2-database']




- name: Configure App
  hosts: application
  gather_facts: true
  become: true
  remote_user: ubuntu
  tasks:

    - name: Rsync provision script to application server
      ansible.posix.synchronize:
        src: /home/ubuntu/application/environment/app_env
        dest: /home/ubuntu/
      tags: ['never', 'ec2-configure', 'ec2-application']

    - name: Rsync app files to application server
      ansible.posix.synchronize:
        src: /home/ubuntu/application/app
        dest: /home/ubuntu/
      tags: ['never', 'ec2-configure', 'ec2-application']

    - name: run provision file
      command: /bin/sh "/home/ubuntu/app_env/provision.sh"
      tags: ['never', 'ec2-configure', 'ec2-application']
